### ISSUE TITLE
LoadOrCompute duplicate compute bug on v1 implementation

### ISSUE THREAD

**Issue by petee-d** [puzpuzpuz/xsync#100]
Hey, I know v1 is a bit out of date, just thought you might be interested in a bug I found on the latest v1 tag (v1.5.2), but which was fixed somewhere in v2.

https://github.com/puzpuzpuz/xsync/blob/v1.5.2/mapof.go#L237

```
					value := valueFn()
					var wv interface{} = valueFn()
```

During insertion of a new value, the `valueFn` is called twice instead of using `value` for `wv`. That's OK for `LoadOrStore`, but causes issues in `LoadOrCompute`, which may end up creating the new object twice and returns a different object from the one that was just inserted.

Not sure what the position on v1 maintenance is, but since upgrading to v2 is a breaking change, it might be worth releasing the fix as v1.5.3, WDYT?

**Comment by puzpuzpuz** [comment]
While v2 is a breaking change, migration should be trivial. I'm afraid I don't have the capacity to support multiple versions and v2 has a number of fixes and performance improvements, so I recommend switching to it. I'm going to update the readme to make it apparent that v1 is discontinued.

**Comment by petee-d** [comment]
No problem, I've already upgraded to v2. Making it apparent v1 is
discontinued and even has known bugs sounds like a good way to address it.
Thanks.

**Comment by puzpuzpuz** [comment]
Thanks for understanding and for bringing this up. I've updated the readme.

**Comment by puzpuzpuz** [comment]
Closing this issue as the readme was updated.
