### ISSUE TITLE
Please improve error handling on methods and interfaces

### ISSUE THREAD

**Issue by dileep315r** [puzpuzpuz/xsync#103]
1. Methods like LoadOrCompute() doesn't have a way to bubble the errors up of the compute function. Could you please elaborate on the error handling strategy used in the project.

**Comment by puzpuzpuz** [comment]
Error handling is not a concern for a concurrent map. This doesn't mean that you can't declare a variable of `error` type in the top level of your function and then initialize it to the need value in `Compute`:
```go
	counts := xsync.NewIntegerMapOf[int, int]()
	var err error

	v, ok := counts.Compute(42, func(oldValue int, loaded bool) (newValue int, delete bool) {
		if oldValue == 42 {
			err = errors.New("something went wrong")
			return 0, true // no need to create a key/value pair
		}
		newValue = 0
		delete = false
		return
	})
	fmt.Printf("err: %v\n", err)
```

**Comment by GraceAtwood** [comment]
Would it be worth adding that pattern to the main README?  Spent a second trying to solve for this as well and seeing your example def helped.

**Comment by puzpuzpuz** [comment]
@GraceAtwood that's a good point, thanks! I'll add an example to the godoc.
