### ISSUE TITLE
In v2 a default hasher (of strings) is missing

### ISSUE THREAD

**Issue by shmul** [puzpuzpuz/xsync#105]
Hi,

The `xsync.StrHash64` function of `v1` was very helpful and it is a shamed it is missing from `v2`. Any reason why you decided not to make `hashString` public? 
I'll be happy to issue a pull request with such a change.

Cheers,
Shmul

**Comment by puzpuzpuz** [comment]
That function was removed in favor of more flexible `hash/maphash`-based hash functions. See an example of such function here: https://github.com/puzpuzpuz/xsync/blob/ace0f0f74f9efcf6f83a907113446b7497eab72d/example_test.go#L21-L32

If you have `string` keys, it's trivial to implement a hash function with `maphash.Hash`:
```go
	func(seed maphash.Seed, s string) uint64 {
		var h maphash.Hash
		h.SetSeed(seed)
		h.WriteString(s)
		return h.Sum64()
	}
```

**Comment by shmul** [comment]
Thanks for the reply. It is well understood and seems right. All I'm asking for is to make it a public utility function as string keys are so common.

**Comment by puzpuzpuz** [comment]
There are [`NewMapOf`](https://pkg.go.dev/github.com/puzpuzpuz/xsync/v2#NewMapOf) and [`NewMapOfPresized`](https://pkg.go.dev/github.com/puzpuzpuz/xsync/v2#NewMapOfPresized) built-in constructor for typed maps with `string` keys, so a separate function is not needed. Sorry for not mentioning this initially.

**Comment by shmul** [comment]
Perfect. Many thanks.

**Comment by puzpuzpuz** [comment]
No problem at all. Feel free to reopen this issue or create a separate one if you find that the library API could be improved.
