### ISSUE TITLE
MPMC queue CPU usage through the roof

### ISSUE THREAD

**Issue by ivanjaros** [puzpuzpuz/xsync#117]
I have a cache where I have a queue for synchronized writes(due to eviction policies).
When I have a simple channel:
```
func (c *cache) run() {
  for {
    select {
        case task := <-c.queue:
           ...
        case <-c.ctx.Done():
          return
    }
 }
}
```

the CPU usage is 0%(the app is not under any load, its just idling). When I switch to the the MPMC queue:
```
func (c *cache) run() {
  for {
    task := c.queue.Dequeue()
    switch {
       case task.foo == "bar":
        ....
    }
 }
}
```

the CPU jumps to over 8%. When I have 5 apps running on localhost with this cache, this takes half of my CPUs while none of the apps are actually doing anything. When I looked at pprof data it looks to me like Go has issue with scheduling.

![prof](https://github.com/puzpuzpuz/xsync/assets/64546059/5434b83b-0e2e-45a0-b221-fae8d6fd7a3f)

I have switched to the queue mostly because in benchmarks it proved 30% saving in memory usage, compared to channel and 3x increase in performance. But when I actually run the app, this happens. So I switched back to channel and CPU is 0% again. So this is the culprit. I do not understand why this is because I have seen this queue used in other caches and I doubt they had the same issues as I do. Maybe I should not use Dequeue()? Or not in this manner in a for loop? But then how should I wait for work?

**Comment by puzpuzpuz** [comment]
In case if there are no items in the queue, `MPMCQueue` simply calls `runtime.Gosched()`. If other goroutines in your program also have nothing to do, this may lead to busy spinning - and that's what you observe.

You may either use `TryDequeue` instead of `Dequeue` followed by a `time.Sleep` call in case when there are no items in the queue. Or you may keep using a native channel - this should have lower latency since goroutines won't be sleeping unconditionally. Both options should lead to much lower CPU utilization when the program is idling.

**Comment by ivanjaros** [comment]
Adding 100ms sleep mitigated the problem but it just seems silly that this happens. I guess this queue is most suitable for places that are crunching a lot of data, which is not my case.

Thanks for the input.

**Comment by ivanjaros** [comment]
@puzpuzpuz one more question - are you by any chance working on one-to-many or many-to-one queue? That would be exactly what I would need for this use case. In theory it should perform better than many-to-many since there is exactly one consumer or producer on one end.

**Comment by puzpuzpuz** [comment]
You're the first one to ask about these types of concurrent queue. So, nothing in-works, but I may add them in future.

**Comment by ivanjaros** [comment]
Well if you think about it, one-to-many or many-to-one, depending on how you look at it, is what Go's channels are. So i guess it is mostly a matter of finding any performance tweaks that could increase performance in the user space.

**Comment by puzpuzpuz** [comment]
Go's channels are basically an MPMC queue synchronized with a single mutex.
