### ISSUE TITLE
`MapOf` - Document zero value in the context of `Load` and whether or not it applies to deleted items during `Range`

### ISSUE THREAD

**Issue by flowchartsman** [puzpuzpuz/xsync#119]
The godoc for [`MapOf.Load`](https://pkg.go.dev/github.com/puzpuzpuz/xsync/v3#MapOf.Load) states the following (emphasis mine):

> Load returns the value stored in the map for a key, **or nil if no value is present**. The ok result indicates whether value was found in the map.

This is probably a copy-and-paste from the non-generic map implementation, since it does not make sense in the context of a generic data structure when the return type is not a pointer. To be more concrete, there _cannot_ be a `nil` return from `MapOf[string, string].Load()`, so it should probably read something like:

> Load returns a value of type V along with an boolean indicating whether the key was present in the map. If the key was not present, value will be the zero value of type V.

This brings up a related question about `MapOf.Range`.  The godoc there says (emphasis mine):

> Range does not necessarily correspond to any consistent snapshot of the Map's contents: no key will be visited more than once, but if the value for any key is stored **or deleted** concurrently, Range may reflect **any mapping** for that key from any point during the Range call.

Here "any mapping" makes sense in the storage context --if one or more Ps stores a value while we are iterating, we might see any one of them or none at all-- but it is unclear what "any mapping" means in the case of deletion. What happens if an entry is deleted before iteration reaches it? Are we guaranteed to never see it, or could we get the zero value instead? The docs here should be specific, since range does not give us any indication if the value we're seeing might have been deleted. This means that, if it is important to us not to use a deleted value in `Range`, we need to synthesize a way to do it ourselves using the zero value of the type. In the case of primitive types, this would mean never storing the zero value directly, while in the case of structs, it would mean ensuring that at least one field is never stored with a zero value, so that we can can use it to check if the entry was deleted.

~I'll also note that the `Range` docs say that it's safe to modify the map during range; does this apply to deletion?~
Edit: I can answer my own last question here; [this test](https://github.com/puzpuzpuz/xsync/blob/1386eb4f0cb3da051cc51a79365e6f9df7668a71/mapof_test.go#L188-L202) seems to spell out pretty clearly that delete while ranging is fine.

**Comment by puzpuzpuz** [comment]
Thanks for the feedback. I'll update the godoc.

> Edit: I can answer my own last question here; [this test](https://github.com/puzpuzpuz/xsync/blob/1386eb4f0cb3da051cc51a79365e6f9df7668a71/mapof_test.go#L188-L202) seems to spell out pretty clearly that delete while ranging is fine.

Yes, map modification while iterating over it is supported.
