### ISSUE TITLE
[Question] Deadlock detection

### ISSUE THREAD

**Issue by sruehl** [puzpuzpuz/xsync#120]
does this library provide features from https://github.com/sasha-s/go-deadlock or is it possible to combine it with it?

**Comment by puzpuzpuz** [comment]
No, this library is not compatible with go-deadlock. It looks like go-deadlock wraps `sync.Mutex`/`sync.RWMutex` structs, so it's not compatible with 3rd-party mutex implementations.

**Comment by puzpuzpuz** [comment]
go-deadlock's overhead is significant as it uses a `sync.Mutex` to synchronize its state. If xsync had it built-in, it'd ruin the multicore scalability which is the library goal.

**Comment by sruehl** [comment]
Fair point, thanks for taking the time answering the questions :)
