### ISSUE TITLE
Readme is not clear (at least not for me :))

### ISSUE THREAD

**Issue by megalepozy** [puzpuzpuz/xsync#124]
In the Readme it's said under the Map header:
`MapOf[K, V] is an implementation with parametrized key and value types. While it's still a CLHT-inspired hash map, MapOf's design is quite different from Map. As a result, less GC pressure and fewer atomic operations on reads.`

It is not clear to me if the last part is referring to MapOf (probably as it was just mentioned) or Map (as it is under that header and was also just mentioned), so which is it?

My needed usage from this library will be to have a map with a string key and maybe a boolean value, it will need to hold millions (can be over 10M) of key/value pairs and every record will be inserted once (without ever getting updated or deleted) and get read multiple times.
Which type do u recommend me to use?
And how can I calculate its RAM allocation?

Thanks!

**Comment by puzpuzpuz** [comment]
`MapOf` is basically a hash table of pointers to the following struct:
```
type entryOf[K comparable, V any] struct {
	key   K
	value V
}
```

`K` is `string` and `V` is `bool` in your case. So, a on 64-bit machine the memory consumption would be at least 10M * (string_header_size + 1 + 8) bytes which is approximately 17MB.

**Comment by megalepozy** [comment]
OK then MapOf it is! 
Thank you for your quick answer! :)
