### ISSUE TITLE
`xsync.MapOf.Load` may lead to key allocation, unlike `sync.Map` and `xsync.Map`

### ISSUE THREAD

**Issue by rabbbit** [puzpuzpuz/xsync#126]
Hi,

First, the blog posts were very helpful, and the library was sound. Thanks for writing all this!

We recently had a case where sync.RWMutex wasn't performing, so we migrated to `sync.Map`. This made me look around for (non-allocating) alternatives, and I found your library—it looks great!

However, it seems like we hit a performance hit that prevents us from migrating - (I'm guessing) the load function is too large, it's not inlined and it's triggering:
- an extra alloc on our hot path
- more painfully, it triggers an alloc per key when we `Range` over the map

I have two reproductions:
- https://go.dev/play/p/HRnzO2bKgZn - `xsync.Map` requires an alloc
- https://go.dev/play/p/pDHI_sd-ZEA - `sync.Map` with an identical code does not.

To explain the use case, we dynamically build a key using `[256]byte` and look it up on the map. Every few seconds, we iterate over the map and collect statistics. We have around 100_000 keys in the map, so the range can take quite a bit of time.

Interestingly, even with the extra alloc your map is still faster in our benchmarks, so a pretty good result :)
```
GraphNewCallNewElementParallelWithExport/-100-12                18.00µ ± 9%   13.01µ ±  7%  -27.75% (p=0.000 n=10)
GraphNewCallNewElementParallelWithExport/-75-12                 13.51µ ± 4%   10.18µ ±  6%  -24.65% (p=0.000 n=10)
GraphNewCallNewElementParallelWithExport/-50-12                 9.228µ ± 6%   7.272µ ±  3%  -21.20% (p=0.000 n=10)
GraphNewCallNewElementParallelWithExport/-25-12                 5.184µ ± 6%   4.375µ ±  7%  -15.59% (p=0.000 n=10)
GraphNewCallNewElementParallelWithExport/-10-12                 3.189µ ± 3%   2.772µ ±  6%  -13.08% (p=0.000 n=10)
GraphNewCallNewElementParallelWithExport/-5-12                  2.520µ ± 7%   2.342µ ±  3%   -7.08% (p=0.007 n=10)
GraphNewCallNewElementParallelWithExport/-2-12                  2.115µ ± 5%   2.171µ ±  4%   +2.67% (p=0.050 n=10)
GraphNewCallNewElementParallelWithExport/-1-12                  2.080µ ± 3%   2.111µ ±  6%        ~ (p=0.089 n=10)
GraphNewCallNewElementParallelWithExport/-0-12                  2.023µ ± 3%   2.131µ ±  2%   +5.36% (p=0.000 n=10)
```
(100->0 is the % of new elements). 

I tried to hack through the code a bit, but it doesn't seem immediately trivial.
- unrolling the inner loop didn't change anything
- I tried to simplify the hasher a bit (fewer closures?) but that didn't change much.

I don't know if solving this is achievable, but I certainly found this interesting.

**Comment by puzpuzpuz** [comment]
More details here: https://github.com/puzpuzpuz/xsync/pull/127#discussion_r1540596896

**Comment by rabbbit** [comment]
I'm not being helpful, closing.
