### ISSUE TITLE
Can xsync.MapOf be encoded/decoded with gob.Encoder as-is?

### ISSUE THREAD

**Issue by karelbilek** [puzpuzpuz/xsync#131]
Can xsync.MapOf be encoded/decoded with gob.Encoder/Decoder?

I *think* it can, but not entirely sure :)

**Comment by karelbilek** [comment]
Ah I think cannot, as there is this in the struct, which gob will not encode

```
type MapOf[K comparable, V any] struct {
...
	hasher       func(K, uint64) uint64
```

I don't think gob can deal with this :/

**Comment by karelbilek** [comment]
No it will definitely fail. Closing this, I guess. (I think gob encoding is a non-goal.)

**Comment by puzpuzpuz** [comment]
Yes, out-of-the-box ser/des is not supported, so you'll need to write some code to extract data from a map and put it back.
