### ISSUE TITLE
Support Go 1.23 Iterators

### ISSUE THREAD

**Issue by amnonbc** [puzpuzpuz/xsync#148]
This would allow the `Range()` function on `Map` to be depricated

**Comment by amnonbc** [comment]
This already works. 
Thanks

**Comment by fiatjaf** [comment]
What do you mean? It works how?

You mean like this?

```go
for k, v := range iter.Seq2[K, V](map.Range) {
    ...
}
```

This works, but would be nice to have a dedicated function yielding a better syntax.

**Comment by amnonbc** [comment]
```
for k, v := range syncmap.Range {
    ...
}
```
also works, as `Range` already has the right signature.
