### ISSUE TITLE
nilVal is not unique

### ISSUE THREAD

**Issue by ericlagergren** [puzpuzpuz/xsync#26]
The compiler is free to make `new(struct{}) == new(struct{})`, and indeed does so. This means `Map` can get confused if and returns `nil` if a  user tries to store `new(struct{})`.

I suggest using the address of a global int, for example.

```
var nilVal int // use &nilVal
```

**Comment by puzpuzpuz** [comment]
Closing this one for now. Please comment if the issue exists and I'll reopen it.

**Comment by ericlagergren** [comment]
> What's get stored in the Map is not *struct{}, but the *interface{}

Gotcha! That works, then. I didn't test anything, just saw `new(struct{})` while glancing over the repo.

**Comment by puzpuzpuz** [comment]
Good to know and thanks once again for the heads up.

If you start using xsync, any feedback is welcome. Experimental PRs are more than welcome as well.
