### ISSUE TITLE
Range Causes extra memory allocations 

### ISSUE THREAD

**Issue by zetoqu** [puzpuzpuz/xsync#44]
Hi,
     Your project and hard-work is very much appreciated. 
     My use case needs the map to be ranged as fast as possible ( Maybe million of times every second and this behavior will continue for entire service duration) . However, the following line
https://github.com/puzpuzpuz/xsync/blob/f620963d48970206baacb55253312a822bafc2ce/mapof.go#L319

cause memory allocation always. ( causing unnecessary garbage and thus GC cycles )
This memory allocation can go away if a fixed array is used instead.

Thank you.

**Comment by puzpuzpuz** [comment]
Thanks for pointing this out. #45 gets rid of allocations and also removes locking which leads to better performance in uncontended cases.
