### ISSUE TITLE
 github.com/puzpuzpuz/xsync@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/puzpuzpuz/xsync/v2")

### ISSUE THREAD

**Issue by merlindru** [puzpuzpuz/xsync#60]
Thank you for releasing 2.0.0!!! This library is awesome :-)

Unfortunately, I can't install 2.0.0 right now:

```bash
$ go get github.com/puzpuzpuz/xsync
go: added github.com/puzpuzpuz/xsync v1.5.2

$ go get github.com/puzpuzpuz/xsync@v2.0.0
go: github.com/puzpuzpuz/xsync@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/puzpuzpuz/xsync/v2")
```

**Comment by merlindru** [comment]
To fix this, we only need to add a `/v2` to the end of this line:

https://github.com/puzpuzpuz/xsync/blob/main/go.mod#L1

**Comment by puzpuzpuz** [comment]
My bad. Thanks for spotting the issue so quickly! Let me release v2.0.1 to fix it.

**Comment by puzpuzpuz** [comment]
v2.0.1 is out and, hopefully, it fixes the problem. Sorry for messing up the release.

**Comment by merlindru** [comment]
Thank you for the quick turnaround 😄 @puzpuzpuz
