### ISSUE TITLE
Built-in hash function for comparable types

### ISSUE THREAD

**Issue by psyhatter** [puzpuzpuz/xsync#70]
Hey @puzpuzpuz
Thanks for such a cool concurrent data synchronization package

I really like the example of a hash function for a comparable structure, because there is no magic in it, math and only
https://github.com/puzpuzpuz/xsync/blob/051117f622763ecb6d970af5d2e8130bcb0e0e96/example_test.go#L16-L32

And this comment gave me the idea to get the built-in hashing function from the map, in a slightly tricky and insecure magical way
https://github.com/puzpuzpuz/xsync/blob/051117f622763ecb6d970af5d2e8130bcb0e0e96/mapof.go#L32-L33

Here's what I got: https://goplay.tools/snippet/w91su4PCNMY
```go
func main() {
	type t struct{ int }

	hash := HashFuncOf[t]()
	if hash == nil {
		log.Fatalln("hash func is nil")
	}

	seed := maphash.MakeSeed()
	a, b := hash.Sum64(seed, t{1}), hash.Sum64(seed, t{1})
	fmt.Println(a == b)

	// Output:
	// true
}
```

This is not safe because future versions of golang may change the internal arrangement of types.
On the other hand, it might be OK if you put this idea in a separate package like `github.com/puzpuzpuz/xsync/unsafehasher` and warn the user about the potential problem in the documentation or init function, like this:
```go
// This init function will prevent the application from starting
// if the internals of golang types change in such a way that
// this package causes a panic.
func init() {
	type t struct{ bool; int; string; float64 }
	HashFuncOf[t]().Sum64(maphash.MakeSeed(), t{})
}
```

Also, the trick has a minus, which consists in the fact that the built-in hash function requires passing by pointer, which can negatively affect performance, but it can probably be reduced using `sync.Pool`

What do you think about supporting this way of creating hash functions?

And yet, it seems that this comment about string keys is superfluous here, apparently accidentally copied from the implementation of `Map`
https://github.com/puzpuzpuz/xsync/blob/051117f622763ecb6d970af5d2e8130bcb0e0e96/mapof.go#L31-L34

**Comment by puzpuzpuz** [comment]
That's a fragile, but cool hack. Maybe it could be exposed in the following way?
```
m := xsync.NewTypedMapOf[Person, int](UnsafeHashFuncOf[Person]())
```

On the other hand, I'm not sure how valuable it would be for potential users. IMO writing a hash function with `hashmap` is an easy task and you usually don't have a lot of maps with different struct key types in your application. WDYT?

> And yet, it seems that this comment about string keys is superfluous here

Thanks, that's a leftover from one of the old version. Removed it in #72.

**Comment by psyhatter** [comment]
That's really amazing!
https://github.com/puzpuzpuz/xsync/blob/7784f4557c8ceaae4040ac2d605be6454a73ec0f/util.go#L51-L57

Well, maybe then make it a generic function and use it if `(MapOf).hasher == nil`?

Something like that:
```go
func builtinhash[T comparable](seed maphash.Seed, v T) uint64 {
	return uint64(memhash64(unsafe.Pointer(&v), uintptr(*(*uint64)(unsafe.Pointer(&seed)))))
}
```

**Comment by puzpuzpuz** [comment]
The function you're referring to assumes 64 bit size only (e.g. int64 or uint64 or uniptr on a 64-bit system). There is a separate `runtime.memhash` which takes an input of arbitrary length and returns its hash. The runtime uses it (and some variations) to calculate a hash of var-length types (`string`) and not only. I guess it's possible to use it to write a versatile hash function, but it's tricky and I didn't want to mess with internals that much. The only reason I used `memhash64` is that the previous function was significantly slower than this hack.

**Comment by rabbbit** [comment]
Should this one be closed given v3 doesn't have the `hasher` parameter?

**Comment by puzpuzpuz** [comment]
True. The built-in hash function is already available in v3.
