### ISSUE TITLE
Map: add way to provide initial size hints

### ISSUE THREAD

**Issue by costela** [puzpuzpuz/xsync#85]
Since the difference in performance caused by map growth is noticeble, it would be great if we could initialize the map with size hints to try to avoid growths on add.

The fact that we spread keys across buckets makes this non-trivial, but maybe it would be enough to assume normally distributed keys and just grow the buckets proportionally to the initial hint?

I've just glossed over the code, but could try a PR if there's no obvious blocker I missed and nobody else beats me to it!

**Comment by puzpuzpuz** [comment]
Yes, it would be a good addition to both `Map` and `MapOf`.

> just grow the buckets proportionally to the initial hint

Yes, I'd simply use `nextPowOf2(size / entriesPerMapBucket)` as the initial table size. That's the usual way to initialize the hash table based on the hint.

**Comment by costela** [comment]
damn, that was fast! I intended to work on this tonight! 😅

Thanks! 🎉

**Comment by puzpuzpuz** [comment]
Thanks for opening this issue.

> I intended to work on this tonight!

If you see any issues or potential improvements around #86, please submit a PR. I won't be releasing the next version for a few days.

**Comment by costela** [comment]
Thanks, will do! 👍🏻
