### ISSUE TITLE
Nesting multiple xsync.MapOf maps not supported, or...?

### ISSUE THREAD

**Issue by grongor** [puzpuzpuz/xsync#91]
Hello! I've been trying out the xsync.MapOf on one of my projects and I ran into a strange issue when nesting the maps. Am I doing something wrong, or did I just discover a bug? Here is a runnable example (using latest xsync version):

```go
package main

import (
	"github.com/puzpuzpuz/xsync"
)

type tmp struct {
	Hello string
}

func main() {
	const stringKey = "test"
	const intKey = 123

	outerStringMap := xsync.NewMapOf[*xsync.MapOf[uint32, *tmp]]()

	innerIntMap, loaded := outerStringMap.LoadOrCompute(stringKey, func() *xsync.MapOf[uint32, *tmp] {
		return xsync.NewIntegerMapOf[uint32, *tmp]()
	})
	if loaded {
		panic("expected nothing")
	}

	innerIntMap.Store(intKey, &tmp{Hello: "world"})

	innerIntMap, loaded = outerStringMap.Load(stringKey)
	if !loaded {
		panic("expected existing map")
	}

	hello, loaded := innerIntMap.Load(intKey)
	if !loaded {
		panic("expected existing value")
	}

	if hello.Hello != "world" {
		panic("unexpected value")
	}
}
```

```txt
grongor@grongor-nb:~/xsync-test$ go run .
panic: expected existing value

goroutine 1 [running]:
main.main()
        /home/grongor/xsync-test/main.go:33 +0x112
exit status 2
```

![image](https://user-images.githubusercontent.com/972493/220422090-23fda7a8-3888-4b28-b6b9-d25eb3b8f54d.png)
![image](https://user-images.githubusercontent.com/972493/220422112-d9407941-0d07-460b-8e6e-65134b3b1f85.png)

**Comment by puzpuzpuz** [comment]
Hi @grongor 

You should import `github.com/puzpuzpuz/xsync/v2`, not `github.com/puzpuzpuz/xsync`. Other than that, I've tried your snippet on go 1.19.3 and saw no panic.

**Comment by grongor** [comment]
OMG I hate this versioning system so much :D Yeah, that was it...thank you very much for the quick response! Sorry for wasting your time :)

Great lib btw!
