### ISSUE TITLE
"Drawbacks" you say?

### ISSUE THREAD

**Issue by FrankDMartinez** [puzpuzpuz/xsync#94]
Hi.

I hope you are having a great new year so far.

In the article at https://gopheradvent.com/calendar/2021/journey-to-a-faster-concurrent-map, you say `xsync.Map` "has some drawbacks". To which drawbacks do you refer?

Thanks in advance.

**Comment by puzpuzpuz** [comment]
Hi @FrankDMartinez

The main drawback is certain GC pressure, i.e. `xsync.Map`/`xsync.MapOf` allocates certain additional structs on the heap. In this respect, a plain `map` + `sync.Mutex` is preferable. On the other hand, any scalable concurrent hashmap implementation relies on GC or GC-like (the latter is applicable to languages with manual memory management, like C/C++).

**Comment by FrankDMartinez** [comment]
Thanks.
